### ISSUE TITLE
Finalize color palette

### ISSUE THREAD

**Issue by chris-perts** [PERTS/perts-ui#20]
[Asana](https://app.asana.com/0/0/1169273579179434/f)

This is mostly about doc cleanup. The [Style Guide](https://app.asana.com/0/0/1169273579179434/f) is still full of discussion rather than being an actual guide on how to use colors.

Chris and Dan should at least discuss how to handle this, and schedule the work appropriately.

**Comment by taptapdan** [comment]
Link to Style Guide https://docs.google.com/document/d/1OLRm8TcnhIVQ-UW0cCWvTjVrbwYlJZVGvjpwAMWoVwQ/edit

**Comment by taptapdan** [comment]
Some thoughts. I'm trying to take advantage of the Ant Design color pages, since it seems like they've put a lot of thought into this. And a lot of use of their Palette Creation Tool to come up with the tints/shades of the inputted color.

## Brand Colors

Our "PERTS Logo Blue" is `#1C9DE3`:

![perts-logo-blue](https://user-images.githubusercontent.com/276924/89562980-9a96d600-d7cf-11ea-8d6f-e85b4aa102b6.png)

Here is the palette generated using `#1C9DE3`:

<img width="1207" alt="Screen Shot 2020-08-06 at 10 30 10 AM" src="https://user-images.githubusercontent.com/276924/89563133-d3cf4600-d7cf-11ea-80b3-027073a5ae8f.png">

I'm not sure what contrast ratio Ant uses to determine white-on-color, but, according to the [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/), it fails WCAG AA against the color white with normal text. Since we do this a lot, I think it would be best to not use this color as our "primary" color.

<img width="728" alt="Screen Shot 2020-08-06 at 10 32 32 AM" src="https://user-images.githubusercontent.com/276924/89563379-36c0dd00-d7d0-11ea-92b6-ebd02060a191.png">

<img width="721" alt="Screen Shot 2020-08-06 at 10 32 50 AM" src="https://user-images.githubusercontent.com/276924/89563391-3aecfa80-d7d0-11ea-9bff-8f92b214936e.png">

Instead, I recommend we select the next shade darker and go with `#0d79bd`, which passes WCAG AA for normal sized text.

<img width="722" alt="Screen Shot 2020-08-06 at 10 37 05 AM" src="https://user-images.githubusercontent.com/276924/89563756-c9fa1280-d7d0-11ea-9808-950a15079765.png">

This allow us to utilize the color for all buttons, text links, and other action UI elements. It also works with "PERTS Logo Blue" so they can appear together and look nice.

I would then select a darker shade to indicate hovers, actives, etc. And the lightest tint for our focus indicator.

<img width="663" alt="Screen Shot 2020-08-06 at 10 40 03 AM" src="https://user-images.githubusercontent.com/276924/89564001-35dc7b00-d7d1-11ea-862f-5687bd9535a0.png">

For our `theme.js` config, I'd suggest we go ahead and place all the tints and shades so that we have other colors to choose from if we need them, and we're not hunting them down months from now. Like:

```js
export const primaryColors = {
  primaryLight6: '#ebfbff',
  primaryLight5: '#c2f2ff',
  primaryLight4: '#99e6ff',
  primaryLight3: '#6fd4fc',
  primaryLight2: '#43b9f0',
  primaryLight1: '#1c9de3', // #000000 accessible, pertsBlue
  primary: '#0d79bd', // #FFFFFF accessible
  primaryDark1: '#035996',
  primaryDark2: '#003e70',
  primaryDark3: '#00264a',
};

export const brandColors = {
  primary: primaryColors.primary,
  focus: primaryColors.primaryLight6,
  active: primaryColors.primaryDark3,
};
```

## Status/Functional Colors

I'm not 100% sure on status/functional colors: in Copilot, places we'd use the InfoBox component, form errors, form success, etc. The WCAG AA accessibility requirements mean we have to go pretty dark for white on ${color}.

<img width="660" alt="Screen Shot 2020-08-06 at 10 55 44 AM" src="https://user-images.githubusercontent.com/276924/89565476-82c15100-d7d3-11ea-9bf0-e8b609fa419c.png">

An alternative would be to go with black (actually `#202020` is our text color) on ${color}, which I **might** like a little better. I like the colors better, but not so crazy about the text. It'd probably grow on me though?

<img width="660" alt="Screen Shot 2020-08-06 at 10 55 48 AM" src="https://user-images.githubusercontent.com/276924/89565553-95d42100-d7d3-11ea-9b8e-8d3af23533b6.png">

## Neutral/Text Colors

The Ant page discusses neutral colors with text. I think it would be useful to include a section on text colors that we're using. I don't agree with Ant because the a lot of those lighter grays aren't accessible.

Is it might be worth at least mentioning that we're using `#202020` as our main text color?

Is it worth mentioning all the other grays that we use in our apps (borders, for example)? It doesn't seem so since I don't see other people on the team needing that really.

## Alternative Color Options

I took a look at the orange color you had selected as a potential "secondary" color in our brand. I like it, but it doesn't meet WCAG AA for normal text against white. And you have to go pretty dark to make it work, to the point that it looks brown to me.

<img width="1203" alt="Screen Shot 2020-08-06 at 11 12 40 AM" src="https://user-images.githubusercontent.com/276924/89566949-c452fb80-d7d5-11ea-8372-9f8a86b129c2.png">

Looking at the Ant colors, I find the magenta palette to be pretty striking, and it still looks like magenta at `color-7`/`magenta-7`, which would pass WCAG AA.

<img width="1201" alt="Screen Shot 2020-08-06 at 10 19 31 AM" src="https://user-images.githubusercontent.com/276924/89566208-9ae5a000-d7d4-11ea-878b-7e4b357f1141.png">

Although, in my opinion, I have yet to come across a scenario the entire time I've worked at PERTS where I would have thought a secondary color would improve the UI.

So, perhaps, we could just include all of the color palettes as options for folks. But let people know that, if they are going to be using it with white-on-{color} or {color as text}-on-white, then it needs to pass the WebAIM Contrast Checker?

This would also provide us with color options for our reports. When used in charts, with no text on top of the color, we're free to use most colors.

## So

That's my brain dump. Give feedback and I can toss stuff into the Style Guide.

**Comment by taptapdan** [comment]
## Data Visualizations

Also! Ant has a really great document on use of colors in data visualizations: https://antv.vision/en/docs/specification/principles/visual

Personally, I'd lean on it pretty heavily if I were designing reports.

**Comment by taptapdan** [comment]
## Color Contrast

I also wanted to mention the `color-contrast` package which calculates the contrast between 2 colors. This might be useful for report generation, to calculate whether white or black on ${color} should be used.

**Comment by chris-perts** [comment]
> Status/Functional Colors

I agree that the two samples you gave (white on very dark colors, and black on brighter colors) aren't great. Maybe we can avoid solid-color backgrounds for status boxes? Seems like a nice thick border, or a nested white-card-inside-colored-card would accomplish a lot and still allow us to use contrast-friendly whites and blacks as text backgrounds.

**Comment by chris-perts** [comment]
> I don't agree with Ant [on neutral colors] because the a lot of those lighter grays aren't accessible.

I checked the 65% opacity white-on-black and black-on-white, and with [this tool](https://contrast-ratio.com/#hsla%28255%2C0%25%2C100%25%2C.65%29-on-black) they give a contrast ratio of 8.6, which is plenty for WCAG (I believe 4.5 is the cutoff?).

Our `#202020` also seems to work fine. But, unlike the the non-neutral colors, I think we can change these on a whim without anyone noticing, so I'm not worried about them. We should just do whatever is convenient.

**Comment by chris-perts** [comment]
I found [this collection of web palettes](https://designshack.net/articles/trends/best-website-color-schemes/) instructive. There are a lot that operate with one hue and a neutral:

* snipcart (primary: gray, highlight: yellow)
* mossio (primary: black, highlight: peach)
* omega yeast (primary: white: highlight: teal)
* farm food (primary: white, highlight: green)
* lucia lash: (primary: white, highlight: black)
* pittori di cinema (primary: yellow: highlight: black)
* baobla (primary: white, highlight: green)
* Jean-Baptiste Kaloya Portfolio (various blue)
* Igor (primary: black, highlight: yellow)

So I hear your point that good design doesn't need a secondary color. There's even one with a palette very close to what we're considering, in all-blue: [canatal.net](https://canatal.net/).

I remain unsure that we can make this work. I'm specifically worried about call-to-action buttons.

👉 here's my request for the next step on this: re-do the colors (just the colors) on perts.net/elevate that provides that attention-getting CTA "get started" button, using your favorite choices for the palette. Take a screenshot and we'll discuss.

**Comment by chris-perts** [comment]
Wait! You did this, I just forgot.

![](https://lh5.googleusercontent.com/olFO_Wb324axc02jta6ybRAEdGggrZKCkvmvDh4vQcFMLZ_Rl1xJuQcRECCWDokAKVn0Tl_Wv1UGooSgaWvhhNy31pRezfmSCHprmp2DirkPVzBNxrKe2jffHiqbnEice6ryye0f)

**Comment by taptapdan** [comment]
![palette-blue](https://user-images.githubusercontent.com/276924/89806725-603d7980-daec-11ea-8741-862a9634ddea.png)
![palette-gray](https://user-images.githubusercontent.com/276924/89806728-62073d00-daec-11ea-8a13-f0b1d282917c.png)
![palette-primary](https://user-images.githubusercontent.com/276924/89806753-67fd1e00-daec-11ea-9b36-110cad69a6cd.png)
![palette-primary-use](https://user-images.githubusercontent.com/276924/89806762-69c6e180-daec-11ea-81f7-6e99cfc5b3dc.png)
![palette-primaryDark](https://user-images.githubusercontent.com/276924/89806768-6cc1d200-daec-11ea-9608-b6b151165199.png)
![palette-primaryDarker](https://user-images.githubusercontent.com/276924/89806777-6e8b9580-daec-11ea-8fd9-543050fa275d.png)
![palette-primaryLight](https://user-images.githubusercontent.com/276924/89806787-70555900-daec-11ea-823f-5e6ee2086d84.png)
